name: 自动更新图片数据
on:
  push:
    paths:
      - 'data/comic_detail_ori.json' # 指定要监听的文件路径
  workflow_dispatch: # 手动运行工作流程

jobs:
  check_file_update:
    runs-on: ubuntu-latest
    steps:
      # 拉取当前github文件
      - name: 拉取文件
        uses: actions/checkout@v2

      - name: 打印文件列表
        run: ls -R
      
      # 配置node环境
      - name: 配置node环境
        uses: actions/setup-node@v1
        with:
          node-version: "18.16.0"

      - name: 安装依赖包
        run: |
          npm install
          npm list 

      # 配置环境变量给js读取，执行js文件
      - name: 运行任务
        run: |
          node script/update_comic_img_size.js
          node script/read_comic_content.js

      # 添加可执行权限
      - name: 添加可执行权限
        run: chmod +x commit.bat

      # 上传文件
      - name: Deploy
        run : |
          git init
          git config --global user.name '${{ secrets.GITHUBUSERNAME }}'
          git config --global user.email '${{ secrets.GITHUBEMAIL }}'
          git add .
          git commit -m "${{ github.event.head_commit.message }} $(date +"%Z %Y-%m-%d %A %H:%M:%S") Updated By Github Actions"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
